
* 2012
*** 2012-06 June
***** 2012-06-08 Friday
******* ps(1) Samples [2012-06-08 Fri 23:44]
I almost forgot. I uploaded over [[http://bit.ly/M1nUBf][16K samples]] of my computer's process state as reported by ps(1). I've been taking a sample every 5 minutes for several months now. I'm going to be using Ruby to [[http://bit.ly/NnoU85][analyze the data]]. While I haven't gotten the numbers yet, I'm certain that my machine has been dying because I've been using Firefox. I'll miss you FF :-(
******* Journalling [2012-06-08 Fri 22:51]
Configured and started using my journal today. If I have it all set up correctly it should get be updated online whenever I deploy my website. I've not yet tried it but I'm pretty sure it will work as I have a robust infrastructure around publishing my website.

******* Baffled By Github [2012-06-08 Fri 22:53]
Suddenly I can't get ssh working with Github. It worked yesterday and I haven't changed anything. I'll figure it out in a day or two.

******* Octopress [2012-06-08 Fri 22:55]
Been [[http://bit.ly/Leebbh][blogging about Octopress]]'s wonders. It is integrating well with Emacs. Most of my Emacs integration is on top of Octopress but I've made just a few changes to the Octopress base code. I've added a few configuration settings. Sent a pull request to have them brought into the mainline Octopress as my changes are backwards compatible. That is, the configuration settings have default values that makes Octopress with my updates behave the same as Octopress without my updates. Maintaining my own =Rakefile= isn't hard but I'd rather not do it.
***** 2012-06-09 Saturday
******* Fix Accursed Github SSH Probem [2012-06-09 Sat 14:25]
I fixed my Github SSH problem. That said, I never figured out what the problem was. I went back to an SSH clean slate by removing my Github SSH keys and moving my [[http://bit.ly/Np5ZtB][SSH config]] file to a temporary location. Then I followed Github's instructions for getting SSH working. Not a hitch. I then moved my SSH config file back into place and everything works. (I need the SSH config file to allow me to use SSH to multiple servers.)
***** 2012-06-11 Monday
******* SPG: Secure Password Generator [2012-06-10 Sun 10:32]
Got tired of all these password cracking cases cause people to have to change many passwords because they reuse same password. Decided to write SCP: The Secure Password Generator. Other password tools exist but mine is going to be simple to use, generate secure passwords, is browser based, never stores passwords on your computer, and, if I manage the CSS, can work on mobile devices too.
***** 2012-06-14 Thursday
******* Facebook User Tracking Blog Posting [2012-06-14 Thu 12:32]
[[http://bit.ly/M7Igbc][Blogged]] about my not-very-happy feelings about Facebook's new tracking program. Very bad.
