#+BEGIN_HTML

---
layout:         post
title:          "SPG: The Secure Password Generator"
date:           2012-06-10 16:48
comments:       true
categories:     [security,passwords,password-generator,projects]
published:      true
---

#+END_HTML
* As Users, We Must Expect Our Passwords To Be Compromised
It is an unfortunate fact that, if you create accounts on websites, some of your passwords will be stolen. For example:
  - There has been a lot of recent press about [[http://linkd.in/Mz4gjU][LinkedIn]]'s recent 6.5M [[http://yhoo.it/Mz4o2T][stolen passwords]]. 
  - In the week since LinkedIn's attack became public, [[http://bit.ly/Mz4yHu][eHarmony]] lost 1.5M passwords in an [[http://lat.ms/Mz4I1y][unrelated attack]]. 
  - Earlier in the year, an undisclosed number of [[http://bit.ly/LLAaXu][Zappos]] 24M users had their [[http://bit.ly/LLAfdJ][passwords compromised]]. 
  - The [[http://bit.ly/LLB5Hl][attack]] on Gawker Media's collection of popular sites ([[http://gaw.kr/LLBedR][Gawker]], [[http://bit.ly/LLBf1y][Lifehacker]], [[http://bit.ly/LLBfhZ][Gizmodo]], [[http://bit.ly/LLBh9N][io9]],[[http://bit.ly/LLBhqe][ Jalopnik]], [[http://bit.ly/LLBfyC][Kotaku]], [[http://deadsp.in/LLBfyD][Deadspin]], and [[http://bit.ly/LLBhqh][Fleshbot]]) in late 2010 that compromised 1.3M accounts shows that this is not a new phenomenon. 

* Cascading Damages
Having your password stolen from a website is a problem. But if you use the same password for many sites, the problem becomes a nightmare. I know that everyone tells you to use [[http://bit.ly/KWPdld][strong passwords]] and to use a different password for each website -- but few people do. A quick look at these [[http://bit.ly/KWPowF][Google search results]] should be convince you that people just don't follow that advice.

* The Reason Behind The Mega-Password Thefts
Despite every assurance made by websites (eg: [[http://bit.ly/LLEqX3][LinkedIn]]'s recent message), the only way a website can lose millions of passwords is if they just didn't bother to follow standard security procedures for storing your password. So LinkedIn, Gawker, Zappos, etc.., didn't care about your password's security until a breach made it into the headlines.
#+HTML: <!-- more -->

As revolting as that fact is, it is accurate.

The trick to securely storing a user's password is rather simple: don't store the user's password as it can't be stolen if it is never stored. 
#+BEGIN_QUOTE
Huh?
#+END_QUOTE

You heard me correctly. Websites should store a <geek vernacular warning> /salted hash/ of your password rather than your password. Understanding the math and computer science behind salted hashes is unimportant. All you need to know is that the technology exists. If you are curious, you can read this [[http://bit.ly/LLGvlN][OWASP article]] about salted hashes.

* An Ounce Of Prevention
The only way to protect yourself against these thefts is to, as everyone will tell you, use a unique, strong password for every site. Don't worry, I won't preach to you. You know that this is what should be done and I know that you know that this should be done.

There are two problems with this:
  1. It is difficult to keep track of so many passwords.
  2. People are astoundingly bad at creating secure passwords.

[[http://bit.ly/KWS3GH][Other than that, how was the play, Mrs. Lincoln?]]

* Tools And Reprogramming Are The Answer
It turns out that the best solution to managing your passwords involves the use of tools and reprogramming. The tools are used to help you create unique passwords as well as remember them. The tools can be simple. For example, a handful of [[http://bit.ly/KWRhcK][dice]] can be used to generate unique and secure passwords.

The reprogramming part is the more difficult. It involves you reprogramming your brain so that you protect yourself. Think of it as /safe surfing/.

* The Answer Is...
The answer is going to be in my next blog posting. I'll present several tools and strategies, including one that I'm currently developing, that work better than carrying around a handful of [[http://bit.ly/KWRc90][zocchihedrons]] :-)
